version: "3.7"

services:
  caddy:
    image: caddy:alpine
    ports:
      - target: 80
        published: 80
        mode: host
        protocol: tcp
      - target: 443
        published: 443
        mode: host
        protocol: tcp
    networks:
      - backend
    volumes:
      - /data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /data/caddy/site:/srv
      - /data/caddy/data:/data
      - /data/caddy/config:/config

networks:
  backend:
    external: true
